name: Terraform Plan on Non-Main Branches

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Terraform Plan
        env:
          TF_VAR_BACKEND_BUCKET: ${{ secrets.TF_VAR_BACKEND_BUCKET }}
          TF_VAR_BACKEND_REGION: ${{ secrets.TF_VAR_BACKEND_REGION }}
          TF_VAR_BACKEND_FILE:   ${{ secrets.TF_VAR_BACKEND_FILE }}

          TF_VAR_variables_bucket_name:   ${{ secrets.TF_VAR_variables_bucket_name }}
          TF_VAR_variables_bucket_file:   ${{ secrets.TF_VAR_variables_bucket_file }}
          TF_VAR_variables_bucket_region: ${{ secrets.TF_VAR_variables_bucket_region }}
        run: |
          export TF_VAR_BACKEND_BUCKET=${{ secrets.TF_VAR_BACKEND_BUCKET }}
          export TF_VAR_BACKEND_REGION=${{ secrets.TF_VAR_BACKEND_REGION }}
          export TF_VAR_BACKEND_FILE=${{ secrets.TF_VAR_BACKEND_FILE }}
          
          export TF_VAR_variables_bucket_name=${{ secrets.TF_VAR_variables_bucket_name }}
          export TF_VAR_variables_bucket_file=${{ secrets.TF_VAR_variables_bucket_file }}
          export TF_VAR_variables_bucket_region=${{ secrets.TF_VAR_variables_bucket_region }}
          
          /usr/local/bin/task tf/install
          /usr/local/bin/task tf/plan
